### ISSUE TITLE
change the type of query search from POST to GET

### ISSUE THREAD

**Issue by abuelnasr0** [adelelwan24/Semantic-Search-project#23]
The current API for (search in videos , search in Papers) is POST request.
The right way to deal with the query search is to create a GET request. for example link will be like that:
```
www.example.com/search?query=what+is+machine+learning&offset=0
```
and then get the request args.

@adelelwan24 
can you change it?

Thanks!

**Comment by adelelwan24** [comment]
Done in the commit with the SHA: [9301e16](https://github.com/adelelwan24/Semantic-Search-project/commit/9301e161cc0262853ee099bf9372107bc563eb12)
